version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  rotating_log:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: ./log.txt
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console, rotating_log]
    propagate: no
root:
  level: INFO
  handlers: [console, rotating_log]